---
Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
  - &Org2
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
  - &Org3
    Name: Org3MSP
    ID: Org3MSP
    MSPDir: crypto-config/peerOrganizations/org3.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
  - &Org4
    Name: Org4MSP
    ID: Org4MSP
    MSPDir: crypto-config/peerOrganizations/org4.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org4MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org4MSP.member')"
  - &Org5
    Name: Org5MSP
    ID: Org5MSP
    MSPDir: crypto-config/peerOrganizations/org5.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org5MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org5MSP.member')"
  - &Org6
    Name: Org6MSP
    ID: Org6MSP
    MSPDir: crypto-config/peerOrganizations/org6.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org6MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org6MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org6MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org6MSP.member')"
  - &Org7
    Name: Org7MSP
    ID: Org7MSP
    MSPDir: crypto-config/peerOrganizations/org7.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org7MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org7MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org7MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org7MSP.member')"
  - &Org8
    Name: Org8MSP
    ID: Org8MSP
    MSPDir: crypto-config/peerOrganizations/org8.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org8MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org8MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org8MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org8MSP.member')"
  - &Org9
    Name: Org9MSP
    ID: Org9MSP
    MSPDir: crypto-config/peerOrganizations/org9.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org9MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org9MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org9MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org9MSP.member')"
  - &Org10
    Name: Org10MSP
    ID: Org10MSP
    MSPDir: crypto-config/peerOrganizations/org10.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org10MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org10MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org10MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org10MSP.member')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application:
  Organizations:
    - *Org1
    - *Org2
    - *Org3
    - *Org4
    - *Org5
    - *Org6
    - *Org7
    - *Org8
    - *Org9
    - *Org10
  Policies: &ApplicationPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer:
  OrdererType: etcdraft
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  EtcdRaft:
    Consenters:
      - Host: orderer.example.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
  Organizations:
    - *OrdererOrg
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  GeneralGenesis:
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *Orderer
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
          - *Org2
          - *Org3
          - *Org4
          - *Org5
          - *Org6
          - *Org7
          - *Org8
          - *Org9
          - *Org10
  GeneralChannelApp:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  SecurityChannelApp:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  MonitoringChannelApp:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  IoTChannelApp:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp5:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp6:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp7:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp8:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp9:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp10:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp11:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp12:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp13:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp14:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp15:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp16:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp17:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp18:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
  ChannelApp19:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5
        - *Org6
        - *Org7
        - *Org8
        - *Org9
        - *Org10
      Capabilities:
        <<: *ApplicationCapabilities
      Policies:
        <<: *ApplicationPolicies
